import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { PAGE_HEADS } from './page-heads';
import { SITEMAP_ENTRIES, SITE_ORIGIN, buildSitemapXml } from './sitemap';

/*
 * The sitemap module, and the file it generates.
 *
 * `document-head.test.ts` already proves the committed XML and `PAGE_HEADS` are the same
 * set. This suite covers what that one cannot: that the committed file is what the
 * *generator* would produce, and that the document is well-formed. Those are the two ways a
 * generated file goes wrong — someone edits the output instead of the source, or the source
 * emits something a parser rejects and nobody looks at the XML again.
 */

const projectFile = (relative: string): string => {
  const path = resolve(process.cwd(), relative);
  try {
    return readFileSync(path, 'utf8');
  } catch {
    throw new Error(`Could not read ${relative} (looked in ${path}). Run vitest from frontend/.`);
  }
};

const COMMITTED = projectFile('public/sitemap.xml');

describe('the committed sitemap is the generated sitemap', () => {
  it('**matches byte for byte**, so a hand-edit cannot survive', () => {
    // The assertion the generated-file comment relies on. Without it, "do not edit" is a
    // request; with it, editing the XML fails the build and names the file to edit instead.
    expect(COMMITTED).toBe(buildSitemapXml());
  });

  it('is regenerated by `npm run sitemap`', () => {
    // Not a behavioural check — a signpost. If the assertion above fails, this is the fix,
    // and a developer reading the failure output should not have to go looking for it.
    expect(COMMITTED).toContain('scripts/generate-sitemap.mjs');
  });
});

describe('the document is well-formed', () => {
  it('declares the sitemap namespace and nothing else', () => {
    expect(COMMITTED.startsWith('<?xml version="1.0" encoding="UTF-8"?>')).toBe(true);
    expect(COMMITTED).toContain('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">');
    expect(COMMITTED.trimEnd().endsWith('</urlset>')).toBe(true);
  });

  it('parses, and every url carries all four elements', () => {
    // A minimal structural parse rather than a real XML parser: the shape is generated from
    // one template, so what is worth checking is that the template produces four children
    // per entry and that the counts agree.
    const blocks = [...COMMITTED.matchAll(/<url>([\s\S]*?)<\/url>/g)].map((m) => m[1]);
    expect(blocks).toHaveLength(SITEMAP_ENTRIES.length);

    for (const block of blocks) {
      expect(block).toMatch(/<loc>https:\/\/zunopilot\.com\/\S*<\/loc>|<loc>https:\/\/zunopilot\.com\/<\/loc>/);
      expect(block).toMatch(/<lastmod>\d{4}-\d{2}-\d{2}<\/lastmod>/);
      expect(block).toMatch(/<changefreq>(daily|weekly|monthly|yearly)<\/changefreq>/);
      expect(block).toMatch(/<priority>[01]\.\d<\/priority>/);
    }
  });

  it('has no unclosed or nested url elements', () => {
    expect(COMMITTED.split('<url>').length).toBe(COMMITTED.split('</url>').length);
    expect(COMMITTED.match(/<urlset/g)).toHaveLength(1);
  });
});

describe('the entries', () => {
  it('are absolute URLs on the canonical origin', () => {
    // A relative `<loc>` is invalid per the protocol, and an origin built from
    // `window.location` would have a preview deployment advertising itself.
    expect(SITE_ORIGIN).toBe('https://zunopilot.com');
    for (const entry of SITEMAP_ENTRIES) {
      expect(entry.path.startsWith('/'), `${entry.path} needs a leading slash`).toBe(true);
      expect(() => new URL(`${SITE_ORIGIN}${entry.path}`)).not.toThrow();
    }
  });

  it('list each URL exactly once', () => {
    const paths = SITEMAP_ENTRIES.map((e) => e.path);
    expect(new Set(paths).size).toBe(paths.length);
  });

  it('**cover every indexable page and nothing else**', () => {
    // The set agreement, asserted against the module rather than the file — so it holds even
    // before the generator has run.
    const indexable = Object.values(PAGE_HEADS)
      .map((h) => h.path)
      .filter((p): p is string => p !== null);

    expect(SITEMAP_ENTRIES.map((e) => e.path).sort()).toEqual(indexable.sort());
  });

  it('exclude every page that sets noindex', () => {
    // Named explicitly rather than derived: these are the URLs a well-meaning edit would add
    // back, because they are real routes that render real pages.
    const advertised = new Set(SITEMAP_ENTRIES.map((e) => e.path));
    for (const path of [
      '/login', '/signup', '/onboarding',
      '/industries',
      '/solutions/lead-management', '/solutions/sales-automation',
      '/solutions/customer-support', '/solutions/marketing-automation',
      '/solutions/customer-engagement',
    ]) {
      expect(advertised.has(path), `${path} is noindex and must not be advertised`).toBe(false);
    }
  });

  it('carry a lastmod that is a real past date, not a build timestamp', () => {
    // The failure this guards is `new Date()` creeping into the generator. Every page
    // claiming today's date is how Google learns to ignore the field entirely.
    const today = '2026-08-13';
    for (const entry of SITEMAP_ENTRIES) {
      expect(Number.isNaN(Date.parse(entry.lastmod)), `${entry.path}: ${entry.lastmod}`).toBe(false);
      expect(entry.lastmod <= today, `${entry.path} claims a future lastmod`).toBe(true);
    }
    // …and not all identical, which is what a clock-driven value would produce.
    expect(new Set(SITEMAP_ENTRIES.map((e) => e.lastmod)).size).toBeGreaterThan(1);
  });

  it('put the home page first, at priority 1.0', () => {
    expect(SITEMAP_ENTRIES[0].path).toBe('/');
    expect(SITEMAP_ENTRIES[0].priority).toBe(1.0);
  });
});

describe('robots.txt points at it', () => {
  it('names the absolute sitemap URL', () => {
    // A relative `Sitemap:` line is ignored, and a sitemap nothing advertises is only found
    // if a crawler guesses the filename.
    expect(projectFile('public/robots.txt')).toContain(`Sitemap: ${SITE_ORIGIN}/sitemap.xml`);
  });
});
